name: Build IslaAndroid APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Descomprimir proyecto
        run: unzip IslaAndroidFixed_APK.zip

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Compilar el APK
        run: ./gradlew assembleDebug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: IslaAndroid-APK
          path: app/build/outputs/apk/debug/app-debug.apk
